title: Hemalatha Aeluru
name: Hemalatha Aeluru
description: Web Developer | Machine Learning Enthusiast
url: "https://aeluruhemalatha.github.io"
repository: aeluruhemalatha/aeluruhemalatha.github.io

author:
  name   : "Hemalatha Aeluru"
  avatar : "/assets/images/hemalatha.jpg"
  bio    : "A dedicated developer with a strong interest in web technologies, machine learning, and building real-world data-driven applications."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/hemalatha-aeluru"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/aeluruhemalatha"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "hemachowdary145@example.com"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default
locale: en-US
markdown: kramdown
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

